site_name: Sqlite Cache

nav:
  - Home: index.md
  - API Reference: ref.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - console
    - json

markdown_extensions:
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:mermaid2.fence_mermaid

plugins:
  - search:
  - mermaid2:
      version: 9.4.3

extra_css:
  - css/docs.css
