site_name: Sqlite Cache
nav:
  - Home: index.md
  - API Reference: ref.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - yaml
    - console

markdown_extensions:
  - pymdownx.superfences

extra_css:
  - css/docs.css
