[tool.coverage.run]
relative_files = true

[tool.coverage.report]
omit = [
    "tests/*",
]

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
