name: CI

on: ["push"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage coveralls
          python -m coverage run -m pytest

      - run: python -m coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
