name: Release

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: "1.1.12"
      - run: poetry config pypi-token.pypi $PYPI_API_TOKEN
      - run: poetry install
      - run: poetry publish --build
